version: '3.9'

services:
  kiosco-db:
    image: postgres:16.1
    container_name: kiosco-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kiosco
    ports:
      - '5433:5432'
    volumes:
      - kiosco_data:/var/lib/postgresql/data
    networks:
      - kiosco-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d kiosco']
      interval: 5s
      timeout: 3s
      retries: 5

  kiosco-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod-runner
    container_name: kiosco-service
    restart: unless-stopped
    depends_on:
      kiosco-db:
        condition: service_healthy
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@kiosco-db:5432/kiosco
      AUTH_SERVICE_URL: http://auth_service:3000/api/v1
    ports:
      - '3002:3000'
    networks:
      - kiosco-network
      - microservices-network
    command: []
networks:
  kiosco-network:
    driver: bridge
  microservices-network:
    external: true

volumes:
  kiosco_data:
    external: false
